[package]
name = "test-window"
version = "0.1.0"
edition = "2021"
build = "build.rs"
[build-dependencies]
cbindgen = "0.20.0"
[lib]
crate-type = ["staticlib"]
name = "test"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
